In [26]:
import numpy as np
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg

## 6.1
Задача. Решите линейную систему:

In [4]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

## 6.3
Задача. Сколько решений имеет линейная система:
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
#np.linalg.solve(A, B)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(B, 0.0001)

(2, 1)

## 6.4
Задача. Вычислите LU-разложение матрицы:
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [27]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73] ])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
print(np.dot(P.transpose(), A) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
