In [2]:
import numpy as np

### 5.1
Задача. Вычислите (5Е)–1, где Е – единичная матрица размера 5х5.

Единичная матрица 5х5 равна сама себе:

In [3]:
a = np.array([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [7, 8, 9, 8, 7], [0, 1, 1, 2, 3], [3, 2, 1, 2, 4]], float)
print(a)

[[1. 2. 3. 4. 5.]
 [4. 5. 6. 7. 8.]
 [7. 8. 9. 8. 7.]
 [0. 1. 1. 2. 3.]
 [3. 2. 1. 2. 4.]]


In [4]:
b = a * 5
print(b)

[[ 5. 10. 15. 20. 25.]
 [20. 25. 30. 35. 40.]
 [35. 40. 45. 40. 35.]
 [ 0.  5.  5. 10. 15.]
 [15. 10.  5. 10. 20.]]


In [5]:
c = b - 1
print(c)

[[ 4.  9. 14. 19. 24.]
 [19. 24. 29. 34. 39.]
 [34. 39. 44. 39. 34.]
 [-1.  4.  4.  9. 14.]
 [14.  9.  4.  9. 19.]]


### 5.2
Задача. Вычислите определитель матрицы:

In [15]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
print(a)
np.linalg.det(a)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


59.999999999999986

### 5.3.1
Задача. Вычислите матрицу, обратную данной:

In [8]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
print(a)
np.linalg.inv(a)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

### 5.3.2
Задача. Приведите пример матрицы 4х4, ранг которой равен 1.

In [16]:
a = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]], float)
print(a)
np.linalg.matrix_rank(a, 0.0001)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


1

### 5.4
Задача. Вычислите скалярное произведение двух векторов: (1, 5) и (2, 8).

In [17]:
a = np.array([1, 5], float)
b = np.array([2, 8], float)
s = np.inner(a, b)
s/(np.linalg.norm(a)*np.linalg.norm(b))

0.9988681377244377

### 5.5
Задача. Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3).

In [18]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print (np.inner(v, c))
w = np.cross(b, c)
print (np.inner(w, a))

228.5
228.5
