# ДЗ 2. Матрицы и матричные операции

In [1]:
import numpy as np

## Часть 1

### Размерности полученных матриц

Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) $AB$, $BA$ - произведения матриц не определены

б) $AB$ - матрица $2\times 3$, $BA$ - произведение матриц не определено  
      
в) $AB$ - матрица $8\times 8$, $BA$ - матрица $3\times 3$

г) $AB$ - матрица $4\times 4$, $BA$ - матрица $4\times 4$  

### Сумма и произведение матриц

Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 + 4 & -2 + (-1) \\
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3 \\
3 & 5
\end{pmatrix}
$

In [3]:
print(f'A + B = \n{a + b}')

A + B = 
[[ 5 -3]
 [ 3  5]]


$A \times B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5 \\
3 \cdot (4) + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}
$

In [4]:
print(f'A x B = \n{np.dot(a, b)}')

A x B = 
[[  4 -11]
 [ 12  -3]]


$B \times A = 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \times \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 + (-1) \cdot 3 & 4 \cdot (-2) + (-1) \cdot 0 \\
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8 \\
15 & 0
\end{pmatrix}
$

In [5]:
print(f'B x A = \n{np.dot(b, a)}')

B x A = 
[[ 1 -8]
 [15  0]]


### Линейная комбинация для матриц

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C = 3 \times \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 \times \begin{pmatrix}
0 & 5\\ 
2 & -1 
\end{pmatrix} + 4 \times \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix} 
3 \cdot 1 - 2 \cdot 0 + 4 \cdot 2 & 3 \cdot 7 - 2 \cdot 5 + 4 \cdot (-4) \\
3 \cdot 3 - 2 \cdot 2 + 4 \cdot 1 & 3 \cdot (-6) - 2 \cdot (-1) + 4 \cdot 1
\end{pmatrix} = \begin{pmatrix} 
11 & -5 \\
9 & -12
\end{pmatrix}  
$

In [6]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

In [7]:
print(f'3A - 2B + 4C =\n {(3*a) + (-2*b) + (4*c)}')

3A - 2B + 4C =
 [[ 11  -5]
 [  9 -12]]


### Вычисление $AA^{T}$ и $A^{T}A$.

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$

$A \times A^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix} 
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) &  5 \cdot 2 + (-2) \cdot 3 \\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix} 
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$

$A^{T} \times A =  \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix} 
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix} 
45 & 0 \\
0 & 14
\end{pmatrix}$

In [8]:
a = np.array([[4, 1], [5, -2], [2, 3]])

In [9]:
print(f'A x A^T = \n {np.dot(a, a.T)}')

A x A^T = 
 [[17 18 11]
 [18 29  4]
 [11  4 13]]


In [10]:
print(f'A^T x A = \n {np.dot(a.T, a)}')

A^T x A = 
 [[45  0]
 [ 0 14]]


### Функция для перемножения двух произвольных матриц

Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [11]:
def dot_matrix(a, b):
    if len(a[0]) == len(b) and len(a) == len(b[0]):
        c = [[0 for _ in range(len(a))] for _ in range(len(b[0]))]
        for m in range(len(a)):
            for n in range(len(a[0])):
                for k in range(len(b[0])):
                    c[m][k] = a[m][n] * b[n][k] + c[m][k]
    return c

In [12]:
a = np.array([[4, 3, 8, 5, 4], [8, 2, 0, 4, 2], [9, 1, 2, 5, 9], [7, 3, 6, 8, 7], [2, 3, 1, 4, 9], [4, 1, 8, 2, 0], [4, 6, 2, 2, 2], [9, 8, 7, 5, 6], [4, 7, 9, 3, 4], [1, 3, 5, 3, 0]])
b = np.array([[2, 9, 7, 5, 0, 4, 0, 8, 5, 0], [6, 5, 1, 1, 1, 4, 8, 2, 9, 3], [9, 8, 0, 2, 2, 6, 6, 7, 2, 8], [4, 3, 5, 6, 9, 1, 0, 3, 9, 0], [0, 3, 5, 3, 9, 5, 5, 8, 7, 4]])

In [13]:
a.shape

(10, 5)

In [14]:
b.shape

(5, 10)

In [15]:
np.dot(a, b)

array([[118, 142,  76,  81, 100, 101,  92, 141, 136,  89],
       [ 44, 100,  88,  72,  56,  54,  26,  96, 108,  14],
       [ 62, 144, 134, 107, 131, 102,  65, 175, 166,  55],
       [118, 171, 127, 119, 150, 119,  95, 184, 195,  85],
       [ 47,  80,  82,  66, 122,  75,  75, 113, 138,  53],
       [ 94, 111,  39,  49,  35,  70,  56,  96,  63,  67],
       [ 70,  94,  54,  48,  46,  64,  70,  80, 110,  42],
       [149, 210, 126, 115, 121, 145, 136, 200, 218, 104],
       [143, 164,  70,  75,  88, 121, 130, 150, 156, 109],
       [ 77,  73,  25,  36,  40,  49,  54,  58,  69,  49]])

In [16]:
%%timeit
np.dot(a, b)

2.45 µs ± 44.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
dot_matrix(a, b)

[[118, 142, 76, 81, 100, 101, 92, 141, 136, 89],
 [44, 100, 88, 72, 56, 54, 26, 96, 108, 14],
 [62, 144, 134, 107, 131, 102, 65, 175, 166, 55],
 [118, 171, 127, 119, 150, 119, 95, 184, 195, 85],
 [47, 80, 82, 66, 122, 75, 75, 113, 138, 53],
 [94, 111, 39, 49, 35, 70, 56, 96, 63, 67],
 [70, 94, 54, 48, 46, 64, 70, 80, 110, 42],
 [149, 210, 126, 115, 121, 145, 136, 200, 218, 104],
 [143, 164, 70, 75, 88, 121, 130, 150, 156, 109],
 [77, 73, 25, 36, 40, 49, 54, 58, 69, 49]]

In [18]:
%%timeit
dot_matrix(a, b)

528 µs ± 2.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Часть 2

### Вычисление определителя

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

1. Вычислить определитель:  

a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$

б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$
    
в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$

---

а) 

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx \cdot sinx - (-cosx) \cdot cosx = 1$

б) 

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$

In [19]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0,9]])
print(f'|A| = {np.linalg.det(a):.0f}')

|A| = 180


в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{vmatrix} = 0$

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'|A| = {np.linalg.det(a):.0f}')

|A| = 0


### Найти определитель

Определитель матрицы $A$ равен $4$. Найти:

а) $det(A^{2})$
    
б) $det(A^{T})$
    
в) $det(2A)$

---

а) $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$
    
б) $det(A^{T})= det(A) = 4$
    
в) $det(2A) = 2^n \cdot det(A) = 2^n \cdot 4$, где $n$ размер матрицы

### Вырожденная матрица

Доказать, что матрица 

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   
вырожденная.

$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2 \cdot 
\begin{vmatrix} 
-14 & 6 \\
 7 & 13 
\end{vmatrix} - 7 \cdot 
\begin{vmatrix} 
4 & 6 \\
-3 & 13
\end{vmatrix} + (-3) \cdot 
\begin{vmatrix} 
4 & -14 \\
7 & 13
\end{vmatrix} =
-2 \cdot (-14 \cdot 13 - 6 \cdot 7) - 7 (4 \cdot 13 - 6 \cdot (-3)) + (-3)\cdot (4 \cdot 7 - (-14)\cdot (-3)) = 0$

Если определитель матрицы равен нулю, то матрица вырожденная.

In [21]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'|A| = {np.linalg.det(a):.0f}')

|A| = 0


### Ранг матрицы

4. Найти ранг матрицы:

а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

---

a) 

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 & 1 \\
1 & 2 & 3
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 & 1 \\
0 & 1 & 2
\end{pmatrix}$

Ранг матрицы равен $2$

In [22]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


б)

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 1\\ 
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3 \\
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 1\\ 
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3\\
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 1\\ 
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3\\
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & -1\\ 
0 & 0 & 0 & -1\\ 
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3\\
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & -1\\ 
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3\\
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0\\ 
\end{pmatrix}$

Ранг матрицы равен $3$

In [23]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3],[2, 3, 5, 6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
